nameOverride: ""
fullnameOverride: ""
replicaCount: 3

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

debug: false
# Leave empty for stdout only
logsPath: ""

domains:
  frontend: chefbook.io
  backend: chefbook.io

limiter:
  rps: 10
  burst: 2
  ttl: 10m

authService:
  name: &authServiceName "chefbook-backend-auth-service"
  port: &authServicePort 8080
  accessTokenKeyFetchInterval: 10m
  dependencyEnabled: true

chefbook-backend-auth-service:
  nameOverride: *authServiceName
  fullnameOverride: *authServiceName
  service:
    port: *authServicePort


imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
