nameOverride: ""
fullnameOverride: ""

image:
  container: "chefbook-backend-api-gateway"
  registry: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []

config:
  develop: false
  # Leave empty for stdout only
  logsPath: ""

  domains:
    frontend: chefbook.io
    backend: chefbook.io

  auth:
    accessTokenKeyFetchInterval: 10m

  limiter:
    rps: 10
    burst: 2
    ttl: 10m

services:
  auth:
    name: chefbook-backend-auth-service
    namespace: ""
    port: 8080
  user:
    name: chefbook-backend-user-service
    namespace: ""
    port: 8080
  subscription:
    name: chefbook-backend-subscription-service
    namespace: ""
    port: 8080
  profile:
    name: chefbook-backend-user-service
    namespace: ""
    port: 8080
  tag:
    name: chefbook-backend-tag-service
    namespace: ""
    port: 8080
  category:
    name: chefbook-backend-category-service
    namespace: ""
    port: 8080
  recipe:
    name: chefbook-backend-recipe-service
    namespace: ""
    port: 8080
  encryption:
    name: chefbook-backend-encryption-service
    namespace: ""
    port: 8080
  shoppingList:
    name: chefbook-backend-shopping-list-service
    namespace: ""
    port: 8080

service:
  type: ClusterIP
  port: 8080

replicaCount: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
